// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell (hyperpolymath)
//
// Rust binding for tree-sitter-k9.
//
// Provides the K9 language definition for use with the tree-sitter Rust crate.
// K9 supports two variants: Kennel (.k9) for YAML-like data and
// Yard/Hunt (.k9.ncl) for Nickel-derived executable configurations.

use std::ffi::c_void;

extern "C" {
    fn tree_sitter_k9() -> *const c_void;
}

/// Returns the tree-sitter [`Language`] for K9.
///
/// # Safety
/// Calls into the C library generated by tree-sitter.
pub fn language() -> tree_sitter::Language {
    unsafe { tree_sitter::Language::from_raw(tree_sitter_k9()) }
}

/// The source of the K9 tree-sitter highlights query.
pub const HIGHLIGHTS_QUERY: &str = include_str!("../../queries/highlights.scm");

/// The source of the K9 tree-sitter locals query.
pub const LOCALS_QUERY: &str = include_str!("../../queries/locals.scm");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_can_load_grammar() {
        let mut parser = tree_sitter::Parser::new();
        parser
            .set_language(&language())
            .expect("Error loading K9 grammar");
    }
}
